---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
      - id: markdownlint
      - id: markdownlint-fix
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.10.2
    hooks:
      - id: markdown-link-check
        args: [-a, "200,206,403,429"]
