#!/usr/bin/env bash
: "${LIBBASH_DIR:?LIBBASH_DIR must be set. Please source libbash/init before other libraries.}"

#------------------------------ Global Variables ------------------------------

#------------------------------ Private Functions -----------------------------

#------------------------------ Public Functions ------------------------------

# Check if command exists
function lb_command_exists(){
  lb_check_args_num "${@}" 1
  command -v "${1}" &> /dev/null
}

# Check if file exists
function lb_file_exists(){
  lb_check_args_num "${@}" 1
  [ -f "${1}" ]
}

# Check is variable is null
function lb_is_null {
  lb_check_args_num "${@}" 1
  [ -z "${1}" ]
}

# Checkifdir exists
function lb_dir_exists() {
  lb_check_args_num "${@}" 1
  [ -d "${1}" ]
}

function lb_is_int() {
  lb_check_args_num "${@}" 1
  # https://stackoverflow.com/a/2210386/1061279
  [[ "${1}" =~ ^-?[0-9]+$ ]]
}

function lb_is_float() {
  lb_check_args_num "${@}" 1
  # https://stackoverflow.com/a/12643073/1061279
  [[ "${1}" =~ ^[+-]?([0-9]*[.])?[0-9]+$ ]]
}

function lb_is_bool() {
  lb_check_args_num "${@}" 1
  case ${1} in
    "true"|1|0|"false") return 0;;
    *) return 1;;
  esac
}
