#!/usr/bin/env bash

if (( BASH_VERSINFO[0] < 4 )); then
  printf "Bash Lib requires bash v4 or greater\n"
  printf "Current Bash Version: %s\n" "${BASH_VERSION}"
  exit 1
fi

# Shell Otions
set -euo pipefail

# Get the relative path to the repo root
# shellcheck disable=SC2034
LIBBASH_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Filter functions and re export only bash-lib functions to subshells
eval "$(declare -F | sed -e 's/-f /-fx /' | grep 'x lb_')"

function lb_lsf(){
  declare -F | sed -e 's/-f /-fx /' | grep 'x lb_'
}
