---
site_name: libbash
site_description: A collection of common bash libraries.
site_author: Nicholas Wilde
site_url: https://nicholaswilde.io/libbash
copyright: Copyright &copy; 2022 Nicholas Wilde
dev_addr: '0.0.0.0:8000'

repo_url: https://github.com/nicholaswilde/libbash
repo_name: nicholaswilde/libbash
edit_uri: "edit/main/docs/"

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/terminal
  # favicon: assets/images/favicon.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tracking
    #  - navigation.expand
    - navigation.top

nav:
  - Home: index.md
  - About: about.md
  - Installation: installation.md
  - Usage: usage.md
  - Libraries:
      - init: libraries/init.md
      - all: libraries/all.md
      - checks: libraries/checks.md
      - git: libraries/git.md
      - file: libraries/file.md
      - helpers: libraries/helpers.md
      - logging: libraries/logging.md
      - script: libraries/script.md
      - str: libraries/str.md
      - url: libraries/url.md
  - Development: development.md
  - Contributing: CONTRIBUTING.md
  - Code of Conduct: CODE_OF_CONDUCT.md

extra:
  social:
    - icon: fontawesome/solid/house
      link: https://nicholaswilde.io/
    - icon: fontawesome/brands/github
      link: https://github.com/nicholaswilde
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/nicholascwilde
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/wildewoodworking/
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/in/nicholaswilde
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/nicholas.wilde/
    - icon: fontawesome/brands/keybase
      link: https://keybase.io/nicholaswilde
    - icon: fontawesome/solid/key
      link: https://github.com/nicholaswilde.gpg

plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: nicholaswilde
      repo: recipes

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
