---
# https://taskfile.dev

version: '3'

vars:
  BATS: ./test/bats/bin/bats
  PORT: 8000

tasks:
  update:
    desc: Update git submodules
    cmds:
      - "cd test"
      - "git submodule update --init --recursive --remote"
  test:
    desc: Run bats-core tests
    cmds:
      - "{{ .BATS }} --tap test"
  test-lib:
    desc: Run bats-core tests on LIB
    cmds:
      - "{{ .BATS }} ./test/{{ .LIB }}.bats"
  new-example:
    desc: Create a new EXAMPLE from template
    cmds:
      - "cp ./templates/example.sh.tmpl  ./examples/{{ .EXAMPLE }}.sh"
      - sed -i 's/{{"{{"}} LIB {{"}}"}}/{{ .EXAMPLE }}/g' ./examples/{{ .EXAMPLE }}.sh
      - "chmod +x ./examples/{{ .EXAMPLE }}.sh"
  new-test:
    desc: Create a new TEST from template
    cmds:
      - "cp ./templates/tests.bats.tmpl ./test/{{ .TEST }}.bats"
      - sed -i 's/{{"{{"}} LIB {{"}}"}}/{{ .TEST }}/g' ./test/{{ .TEST }}.bats

  new-doc:
    desc: Create a new DOC from teomplate
    cmds:
      - "cp ./templates/doc.md.tmpl ./docs/libraries/{{ .DOC }}.md"
      - sed -i 's/{{"{{"}} LIB {{"}}"}}/{{ .DOC }}/g' ./docs/libraries/{{ .DOC }}.md

  new-script:
    desc: Create a new SCRIPT from template
    cmds:
      - "cp ./templates/script.sh.tmpl ./{{ .SCRIPT }}.sh"
      - "chmod +x ./{{ .SCRIPT }}.sh"
  new-lib:
    desc: Create a new LIB from template
    cmds:
      - "cp ./templates/lib.tmpl ./{{ .LIB }}"
      - task: new-example
        vars:
          EXAMPLE: "{{ .LIB }}"
      - task: new-test
        vars:
          TEST: "{{ .LIB }}"
  serve:
    desc: >-
      Start development server on http://0.0.0.0:{{ .PORT }} using
      Docker and mkdocs-material
    cmds:
      - >-
        docker run --rm -it -p {{ .PORT }}:{{ .PORT}} -v ${PWD}:/docs
        --platform linux/amd64 squidfunk/mkdocs-material serve
        --dev-addr 0.0.0.0:{{ .PORT }} -f ./mkdocs.yml
  default:
    cmds:
      - task -l
    silent: true
