---
# https://taskfile.dev

version: '3'

tasks:
  new-script:
    desc: Create a new SCRIPT from template
    cmds:
      - cp ./templates/script {{ .SCRIPT }}.sh
  new-lib:
    desc: Create a new LIB from template
    cmds:
      - cp ./templates/lib {{ .LIB }}
  default:
    cmds:
      - task -l
    silent: true
