#!/bin/bash

# shellcheck source=/dev/null
source ./libbash/init
# source "${LIBBASH_DIR}/all"
# source "${LIBBASH_DIR}/logging"
# source "${LIBBASH_DIR}/str"
# source "${LIBBASH_DIR}/file"
# source "${LIBBASH_DIR}/checks"
